### PR TITLE
Don't default to the postgres user

### PR DESCRIPTION
**Pull request by shaneog**
This allows more flexibility to have a host that uses the client user name and password, rather than hardcoding the username.

### CODE REVIEW

**Review by robertobarreda — APPROVED** [review]

**Comment by nielsonsantana** [comment]
@shaneog,
I think that instead of `${DB_USER:+user=${DB_USER}}` would be only `user=${DB_USER}`.

**Comment by joekohlsdorf** [comment]
@nielsonsantana Why? When forwarding the clients user name, it is necessary that you don't specify `user` at all.

PR looks good to me and just today needed exactly this 👍

**Comment by nielsonsantana** [comment]
@joekohlsdorf, I agree.

**Comment by shaneog** [comment]
@brainsam Any chance of getting this merged?

**Review by brainsam — APPROVED** [review]

**Pull request merged**
